apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: payment-service
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: payment-service
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: neobank

images:
  - name: neobank/payment-service
    newName: PLACEHOLDER_REGISTRY/neobank/payment-service
    newTag: latest
