apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neobank

resources:
  - namespace.yaml
  - kubecost-config.yaml
  - resource-quotas.yaml
  - limit-ranges.yaml
  - cost-allocation-labels.yaml
  - budget-alerts.yaml
  - metrics-exporter.yaml
