apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
  - namespace.yaml
  - velero-config.yaml
  - backup-schedules.yaml
  - restore-procedures.yaml
  - dr-testing.yaml
  - failover-config.yaml
