apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gatekeeper-config.yaml
  - constraint-templates.yaml
  - constraints.yaml
  - audit-config.yaml
  - exemptions.yaml
