apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
  labels:
    app.kubernetes.io/name: gatekeeper
    app.kubernetes.io/part-of: neobank-platform
    admission.gatekeeper.sh/ignore: "true"
    control-plane: controller-manager
