apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: frontend
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: frontend
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: neobank

images:
  - name: neobank/frontend
    newName: PLACEHOLDER_REGISTRY/neobank/frontend
    newTag: latest
