apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neobank-ingress
  namespace: neobank
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # Enable CORS
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  ingressClassName: nginx
  rules:
    # Frontend
    - host: neobank.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

    # API Gateway pattern - route to different services by path
    - host: api.neobank.local
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 8081
          - path: /api/v1/accounts
            pathType: Prefix
            backend:
              service:
                name: ledger-service
                port:
                  number: 8082
          - path: /api/v1/transactions
            pathType: Prefix
            backend:
              service:
                name: ledger-service
                port:
                  number: 8082
          - path: /api/v1/transfer
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8083
          - path: /api/v1/products
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 8084
          - path: /api/v1/cards
            pathType: Prefix
            backend:
              service:
                name: card-service
                port:
                  number: 8085
