apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neobank

resources:
  - namespace.yaml
  - service-accounts.yaml
  - external-secrets-new.yaml
  - configmap-new.yaml
  - identity-service.yaml
  - ledger-service.yaml
  - payment-service.yaml
  - product-service.yaml
  - card-service.yaml
  - frontend.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policies.yaml
  - pod-disruption-budgets.yaml

commonLabels:
  app.kubernetes.io/part-of: neobank
  app.kubernetes.io/managed-by: kustomize
